image:
  repository: cloudbees-days/hackers-auth
  tag: latest
  pullPolicy: IfNotPresent

hostname: hackers-auth.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  port: 8080 