apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hackers-auth
  labels:
    app: hackers-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackers-auth
  template:
    metadata:
      labels:
        app: hackers-auth
    spec:
      containers:
        - name: hackers-auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10 